### ISSUE TITLE
Invalid numeric argument -Wl in Visual Studio 2022

### ISSUE THREAD

**Issue by fschutt** [Hywan/inline-c-rs#20] opened 2022-09-12 20:50 UTC
https://github.com/Hywan/inline-c-rs/blob/92274c8b5c222e15964b4d4b91b393d6d1911191/src/run.rs#L178-L180

... errors out on Windows 11, Visual Studio 2022 with `invalid numeric argument: -Wl,-rpath,C://Users/.../release` (D8021).

**Comment by camio** [comment] 2024-09-14 01:48
This is a duplicate of #8

**Closed as completed** 2024-09-16 06:31 UTC
